name: Example Workflow

on:
  push:
    branches:
      - develop

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use the secret
        env:
          TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}  # Menggunakan secret di sini
        run: |
          echo "Using TWILIO_AUTH_TOKEN: $TWILIO_AUTH_TOKEN"
          # Anda dapat menggunakan nilai secret dalam tindakan ini
